apiVersion: v1
kind: Pod
metadata:
  name: grafanademo
  labels:
    app: hellografana
spec:
  containers:
  - name: k8s-demo
    image: grafana/grafana:4.6.3
    ports:
    - name: grafana-port
      containerPort: 3000
